# Generated by Django 6.0 on 2025-12-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_read'),
        ('therapy', '0004_remove_session_notes_session_amount_session_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_messages', to='therapy.session'),
        ),
    ]
