# Generated by Django 6.0 on 2025-12-21 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_session'),
        ('therapy', '0005_remove_session_amount_remove_session_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='therapy.session'),
        ),
    ]
