# Generated by Django 6.0 on 2025-12-21 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_remove_session_notes_session_amount_session_is_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='session',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='session',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='therapy.session')),
            ],
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
