# Generated by Django 6.0 on 2025-12-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_remove_session_amount_remove_session_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='session',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
