# Generated by Django 6.0 on 2025-12-21 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0006_session_amount_session_is_paid_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='What is the issue?')),
                ('advice', models.TextField(help_text='General mental health advice')),
                ('medicines', models.TextField(blank=True, help_text='List medicines if any', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='therapy.session')),
            ],
        ),
    ]
