# Generated by Django 6.0 on 2025-12-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0008_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('single', 'Single Session'), ('couple', 'Couple Session')], default='single', max_length=10),
        ),
    ]
